export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const User_CLEAN_ERROR = "User_CLEAN_ERROR";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const USER_UpdateProfile_REQUEST = "USER_UpdateProfile_REQUEST";
export const USER_UpdateProfile_SUCCESS = "USER_UpdateProfile_SUCCESS";
export const USER_UpdateProfile_FAIL = "USER_UpdateProfile_FAIL";
export const UpdateProfile_ErrorClean = "clean_UpdateProfile_Error";
export const USER_UpdateProfile_RESET = "USER_UpdateProfile_RESET";

export const USER_CHANGEPASSWORD_REQUEST = "USER_CHANGEPASSWORD_REQUEST";
export const USER_CHANGEPASSWORD_SUCCESS = "USER_CHANGEPASSWORD_SUCCESS";
export const USER_CHANGEPASSWORD_FAIL = "USER_CHANGEPASSWORD_FAIL";
export const USER_CHANGEPASSWORD_ErrorClean = "USER_CHANGEPASSWORD_ErrorClean";
export const USER_CHANGEPASSWORD_RESET = "USER_CHANGEPASSWORD_RESET";

export const USER_FORGETPASSWORD_REQUEST = "USER_FORGETPASSWORD_REQUEST";
export const USER_FORGETPASSWORD_SUCCESS = "USER_FORGETPASSWORD_SUCCESS";
export const USER_FORGETPASSWORD_FAIL = "USER_FORGETPASSWORD_FAIL";
export const USER_FORGETPASSWORD_ErrorClean = "USER_FORGETPASSWORD_ErrorClean";
export const USER_FORGETASSWORD_RESET = "USER_FORGETASSWORD_RESET";

export const USER_ADDADDRESS_REQUEST = "USER_ADDADDRESS_REQUEST";
export const USER_ADDADDRESS_SUCCESS = "USER_ADDADDRESS_SUCCESS";
export const USER_ADDADDRESS_FAIL = "USER_ADDADDRESS_FAIL";


